# EXCEPTIONS
try:
    n1 = int(input("Mete un numero: "))
except Exception as e:
    print("Da error!")
else:
    print("Todo fue bien")